name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at midnight Jakarta time (UTC+7)
    - cron: "0 17 * * *"

jobs:
  update-readme:
    name: Update Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCALE: "en"
          SHOW_LOC_CHART: "False"
          SHOW_TOTAL_CODE_TIME: "False" 
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROJECTS: "False"